Gilles/routes des connexion
coworking-metz/tickets-backend pull request #1
Opened 2023-08-11 13:40 UTC by gfra54

2023-09-08 15:08 UTC, jdesboeufs requested changes
Si possible scinder cette PR en 3 parties :
- effort de documentation du code existant
- évolutions de l'environnement de dev
- fonctionnalité réelle apportée par cette PR

2023-09-08 15:08 UTC, jdesboeufs commented on .env.sample
> +WP_COWO_API_URL=https://www.coworking-metz.fr/api-json-wp/cowo/v1
Pourquoi ne pas utiliser l'APIv2 déjà installée ?

2023-09-08 15:08 UTC, jdesboeufs commented on .gitignore
> +/doc
Pourquoi ?

2023-09-08 15:08 UTC, jdesboeufs commented on server.js
> +    res.send({ status: 'ok' })
Convention xo

2023-09-08 15:08 UTC, jdesboeufs commented on server.js
> +    const { from, to } = parseFromTo(req.query.from, req.query.to)
Convention xo

2023-09-08 15:08 UTC, jdesboeufs commented on server.js
> +  app.use('/doc', express.static(path.join(__dirname, 'doc')));
Dans le .gitignore??

2023-09-08 15:08 UTC, jdesboeufs commented on server.js
> +    saveUninitialized: true,
Pourquoi ?

2023-09-11 09:55 UTC, gfra54 commented on .gitignore
> +/doc
sinon la doc (generée avec apidoc) est publique et j'ai peur quelle contienne des "infos sensibles". j'attends qu'elle soit clean avant de la rendre publique

2023-09-15 12:31 UTC, closed without merging