Gilles/route ping
coworking-metz/tickets-backend pull request #14
Opened 2023-09-15 12:30 UTC by gfra54

Ajout d'une route /api/ping qui vérifie le statut de l'app (node + MongoDB.
) * Elle retourne un objet JSON indiquant si l'app est 'en marche' ('up') ou 'en panne' ('down').
 * Si l'app est en panne, la fonction retournera un code de statut HTTP 503 (Service non disponible).

2023-09-15 12:37 UTC, jdesboeufs requested changes
Peut-être expliquer à quoi sert le fichier postman et comment on l'utilise.

2023-09-15 12:37 UTC, jdesboeufs commented on lib/ping.js
> +    res.json(payload)
send à la place de json pour rester cohérent avec tout le reste du code

2023-09-15 13:42 UTC, gfra54 commented on lib/ping.js
> +    res.json(payload)
Yes. je met ça dans le README ?

2023-09-15 16:44 UTC, gfra54 commented
> Oui dans le README c'est une bonne idée 👍

j'ai mis dans le readme est ces generique : ca explique comment utiliser n'importe quel json de postman

2023-09-15 21:00 UTC, jdesboeufs commented on lib/ping.js
> +    res.json(payload)
Quel rapport ?

2023-09-15 21:01 UTC, jdesboeufs commented on server.js
> +  app.get('/api/ping', w(ping))
Comme on veut, moi j'appelle aussi ces routes `/ping`.

2023-09-16 05:24 UTC, gfra54 commented on lib/ping.js
> +    res.json(payload)
j'ai pas répondu au bon message -_-

2023-09-19 18:33 UTC, jdesboeufs commented
Remplacé par #17 (à titre d'exemple de bonnes pratiques)

2023-09-19 18:33 UTC, closed without merging