Gilles/ajout nodemon
coworking-metz/tickets-backend pull request #7
Opened 2023-09-11 12:58 UTC by gfra54

J'ai ajouté nodemon dans une commande moins habituelle que 'dev'.
j'ai aussi été obligé de désactiver la connexion à netatmo en developpement car ça ne fonctionne pas (oui je sais c'est pas très contextuel mais le but de cette PR était d'avoir un env de dev "fonctionnel" 🥲)

2023-09-14 07:56 UTC, gfra54 commented on package.json
> +    "dev": "node server",
Oui

2023-09-15 12:27 UTC, gfra54 commented on lib/netatmo.js
> +  if (process.env.NODE_ENV === 'development') {
je l'ai mis dans mon .env local sinon ça marche bien non ?

2023-09-15 20:55 UTC, jdesboeufs requested changes

2023-09-15 20:55 UTC, jdesboeufs commented on lib/netatmo.js
> +  if (process.env.NODE_ENV === 'development') {
Je préfère qu'on corrige le problème plutôt que le contourner de cette façon, qui plus est non standard.

2023-09-15 20:55 UTC, jdesboeufs commented on lib/netatmo.js
> +  if (process.env.NODE_ENV === 'development') {
La convention habituelle c'est que les bibliothèques fonctionnent en mode développement (quand elles en ont un) sauf si `NODE_ENV=production`. L'autre cas particulier est `test`.
C'est notamment le comportement adopté par Express.

2023-09-15 20:55 UTC, jdesboeufs commented on package.json
> +    "dev-nodemon": "nodemon server",
Je vois pas trop l'intérêt entre savoir qu'il faut taper `yarn dev-nodemon` et taper `nodemon server` qui est un choix d'outil perso qui regarde chacun :)

2023-09-15 20:55 UTC, jdesboeufs commented on package.json
> +}
Couic

2023-09-15 20:55 UTC, jdesboeufs commented on lib/netatmo.js
> +  if (process.env.NODE_ENV === 'development') {
Autre possibilité, créés une variable d'environnement `DISABLE_NETATMO` qui par défaut vaut `0` et si elle vaut `1` (configuré via ton `.env`) alors le service ne se lance pas. Mais c'est au dessus qu'il faut le gérer et pas avec un `return`.

2023-09-16 06:51 UTC, gfra54 commented on lib/netatmo.js
> +  if (process.env.NODE_ENV === 'development') {
> Autre possibilité, créés une variable d'environnement `DISABLE_NETATMO` qui par défaut vaut `0` et si elle vaut `1` (configuré via ton `.env`) alors le service ne se lance pas. Mais c'est au dessus qu'il faut le gérer et pas avec un `return`.

Oui en effet j'aurai du faire ça.

2023-09-19 19:11 UTC, closed without merging